name: Java CI Build

# Define the trigger for the workflow (e.g., on push to the main branch or a PR)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs in the workflow
jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment for the build

    steps:
    - name: Check out code
      uses: actions/checkout@v2  # Checkout the code from the repository

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Specify the version of Java to use
        distribution: 'adoptopenjdk'

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository  # Cache the Maven dependencies to speed up the build process
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install -DskipTests  # Build the project using Maven, skipping tests

    - name: Run tests
      run: mvn test  # Run tests using Maven

    - name: Build Docker Image
      run: |
        docker build -t your-dockerhub-username/demo-app .
        docker tag your-dockerhub-username/demo-app your-dockerhub-username/demo-app:latest
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push your-dockerhub-username/demo-app:latest

    - name: Upload build artifacts (optional)
      uses: actions/upload-artifact@v3
      with:
        name: demo-app-artifact
        path: target/demo-0.0.1-SNAPSHOT.jar
